---
name: "✋ Short"
description: | 
   Want a super brief (<60s) summary of one of the topics in the course? Great! Let me know and I'll write it up.
labels:
  - short
assignees:
  - andrewhowdencom
body:
  - type: textarea
    id: short
    attributes:
      label: "What should the content of the short?"
      description: Literally, what is the script of the short.
      placeholder: "Let's talk about <observability|the observability course>"
  - type: checkboxes
    id: topic
    attributes:
      label: Topic
      description: Let's talk about...
      options:
        - label: "#Observability"
        - label: "#PITO (The practical introduction to observability)"
        - label: "The #CourseProgress"