---
name: 🚧 Practical
description: A practical is a directed path involving a technology and applying it in a context (e.g. a project)
title: "[Practical] ..."
labels: ["practical"]
assignees:
  - andrewhowdencom

body:
  - type: textarea
    id: capability
    attributes:
      label: Capability
      description: After completing the practical, learners should be able to do ...
      placeholder: "View data that describes the utilization of CPU cores on a Linux based machine"